jobs:
- name: hello-world
  plan:
  - task: hello-world
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: ((repo))
      run:
        path: echo
        args:
        - ((message))
